### ISSUE TITLE
Add option to set request_timeout

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/jupyterhub-idle-culler#26]
### Proposed change

We're using jupyterhub-idle-culler 1.1 with jupyterhub 1.2.2. We have over 5300 users in the hub database which is causing the `GET /users` request to timeout in some cases:

```
May 10 13:06:21 hub-6b7ffdb6bb-tsbzx hub [E 210510 18:06:21 ioloop:761] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f1a990612b0>>, <Future finished exception=HTTP 599: Operation timed out after 20000 milliseconds with 0 bytes received>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 120, in cull_idle
        resp = yield fetch(req)
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 113, in fetch
        return (yield client.fetch(req))
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
        value = future.result()
    tornado.curl_httpclient.CurlError: HTTP 599: Operation timed out after 20000 milliseconds with 0 bytes received
May 10 13:06:50 hub-6b7ffdb6bb-tsbzx hub INFO INFO 2021-05-10T18:06:50.887Z [JupyterHub log:181] 200 GET /hub/api/users (cull-idle@::1) 49521.67ms
```

The default timeout of 20 seconds is coming from tornado:

https://github.com/tornadoweb/tornado/blob/v6.1.0/tornado/httpclient.py#L349

### Alternative options

We have pycurl installed (version 7.43.0.6) so as a workaround I'm seeing if setting `max-time = 60` in `$HOME/.curlrc` will help but it'd be nice to not have to inject that into our hub image if we can just specify the request timeout to the `cull-idle` script as an argument.

### Who would use this feature?

Anyone with a large number of users in their hub for which requests can take longer than 20 seconds.

### (Optional): Suggest a solution

Add a `--request-timeout` option which if set will be passed to the `HTTPRequest` constructor, else it won't and we'll get the default from tornado.

**Comment by mriedem** [comment]
Alternative suggestion from @minrk:

![image](https://user-images.githubusercontent.com/3237936/118283682-3e1ac280-b495-11eb-968d-d216e4b8e85b.png)

That'd work as well, it'd be nice if that default was at least overridable via environment variable though if a CLI option isn't added.
